const HOUR_WORKING_PER_DAY = 4;
const FULL_TIME_TYPE = 0;
const PART_TIME_TYPE = 1;
const SHAREHOLDER_STATUS = 1;
const NON_SHAREHOLDER_STATUS = 0;

module.exports = {
    HOUR_WORKING_PER_DAY,
    FULL_TIME_TYPE,
    PART_TIME_TYPE,
    SHAREHOLDER_STATUS,
    NON_SHAREHOLDER_STATUS,
};
